# Site settings
title: Jonathan Schapiro's Blog
email: jschapir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! My name is Jonathan Schapiro and I am a Full Stack Software Developer. I come to you from San Francisco, CA by way of Boca Raton, FL.
  I am interested in all things that involve a little bit of thought behind it. I hope you enjoy reading about my journey.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
